window.dashboardSeed = {
  meta: {
    mode: "Sample V2",
    lastUpdated: "2026-05-20",
    sprint: "IBD Assist Build-In-Public",
  },
  teamChannels: [
    {
      id: "ch-001",
      owner: "Devin",
      platform: "TikTok",
      handle: "@devinmerkel",
      role: "Founder organic",
      status: "Needs connection",
      priority: "P0",
      pullMethod: "API/export",
      lastPulled: "Not connected",
    },
    {
      id: "ch-002",
      owner: "Devin",
      platform: "Instagram Reels",
      handle: "@devinmerkel",
      role: "Founder organic",
      status: "Needs Meta permissions",
      priority: "P0",
      pullMethod: "Instagram Graph API",
      lastPulled: "Not connected",
    },
    {
      id: "ch-003",
      owner: "X Scale",
      platform: "YouTube Shorts",
      handle: "@xscale",
      role: "Brand channel",
      status: "API-ready",
      priority: "P0",
      pullMethod: "YouTube Analytics API",
      lastPulled: "Not connected",
    },
    {
      id: "ch-004",
      owner: "X Scale",
      platform: "Instagram Reels",
      handle: "@xscale",
      role: "Brand channel",
      status: "Needs Meta permissions",
      priority: "P0",
      pullMethod: "Instagram Graph API",
      lastPulled: "Not connected",
    },
    {
      id: "ch-005",
      owner: "Austin",
      platform: "TikTok",
      handle: "@austinnormanads",
      role: "Team organic",
      status: "Needs connection",
      priority: "P1",
      pullMethod: "API/export",
      lastPulled: "Not connected",
    },
    {
      id: "ch-006",
      owner: "IBD Assist",
      platform: "Instagram Reels",
      handle: "@ibdassist",
      role: "Demo brand channel",
      status: "Needs Meta permissions",
      priority: "P1",
      pullMethod: "Instagram Graph API",
      lastPulled: "Not connected",
    },
  ],
  joinLinks: [
    {
      id: "jl-001",
      owner: "Austin",
      platform: "TikTok",
      label: "Austin TikTok",
      skoolInviteLink: "Paste Austin's actual Skool invite link",
      status: "Needs link",
      creditedJoins: 0,
      lastImported: "Not imported",
      notes: "Use Austin's native Skool invite/referral link directly in TikTok bio.",
    },
    {
      id: "jl-002",
      owner: "Devin",
      platform: "Instagram",
      label: "Devin Instagram",
      skoolInviteLink: "Paste Devin's actual Skool invite link",
      status: "Needs link",
      creditedJoins: 0,
      lastImported: "Not imported",
      notes: "Use Devin's native Skool invite/referral link directly in Instagram bio.",
    },
    {
      id: "jl-003",
      owner: "X Scale",
      platform: "YouTube",
      label: "X Scale YouTube",
      skoolInviteLink: "Paste X Scale/native Skool invite link if available",
      status: "Needs link",
      creditedJoins: 0,
      lastImported: "Not imported",
      notes: "Use the cleanest Skool link available for the brand channel.",
    },
    {
      id: "jl-004",
      owner: "IBD Assist",
      platform: "Instagram",
      label: "IBD Assist Instagram",
      skoolInviteLink: "Paste IBD Assist Skool invite link",
      status: "Needs link",
      creditedJoins: 0,
      lastImported: "Not imported",
      notes: "Use this if IBD Assist content directly sends people to the group.",
    },
  ],
  teachingTopics: [
    {
      id: "t-001",
      title: "How to choose the product or offer to launch first",
      type: "Course lesson",
      status: "Teach next",
      stage: "Offer",
      priority: "P0",
      demand: 9,
      evidence: "Multiple new members are asking where to start the AI sprint.",
      source: "Skool questions",
      recommendedFormat: "5-minute Start Here lesson",
      owner: "X Scale",
      scheduledFor: "Next Start Here update",
      output: "Product selection checklist",
      next: "Record a short decision-tree lesson and pin it in Start Here.",
    },
    {
      id: "t-002",
      title: "Can Odyssey launch ads or only write them?",
      type: "Live clip + FAQ",
      status: "Teach next",
      stage: "Ads",
      priority: "P0",
      demand: 8,
      evidence: "Members need clarity on Odyssey launch management before Tuesday calls.",
      source: "Skool question + Odyssey demo content",
      recommendedFormat: "Tuesday launch walkthrough clip",
      owner: "X Scale",
      scheduledFor: "Tuesday",
      output: "FAQ post and clipped launch demo",
      next: "Clip the Tuesday section where the campaign is named, checked, and launched.",
    },
    {
      id: "t-003",
      title: "Launch a landing page with AI in 10 minutes",
      type: "Course lesson",
      status: "Planned",
      stage: "Page",
      priority: "P1",
      demand: 7,
      evidence: "High-performing social content and core gap in the Monday workflow.",
      source: "Instagram Reel + first course plan",
      recommendedFormat: "Screen-recorded course lesson",
      owner: "Devin",
      scheduledFor: "Week 1",
      output: "Landing page brief and first draft",
      next: "Use the IBD Assist offer brief and show Claude Code/Codex creating the draft.",
    },
    {
      id: "t-004",
      title: "Name your ads so Friday optimization works",
      type: "Course lesson",
      status: "Taught",
      stage: "Ads",
      priority: "P1",
      demand: 6,
      evidence: "YouTube Shorts demo was useful and should become reusable onboarding.",
      source: "Odyssey demo clip",
      recommendedFormat: "Template lesson",
      owner: "X Scale",
      scheduledFor: "Completed",
      output: "Naming convention template",
      next: "Turn the clip into a downloadable naming template.",
    },
    {
      id: "t-005",
      title: "What signal matters before purchases?",
      type: "Live teaching segment",
      status: "Backlog",
      stage: "Optimization",
      priority: "P1",
      demand: 6,
      evidence: "Friday decision tree content got saves and this comes up before CPA exists.",
      source: "Course clip + expected Friday questions",
      recommendedFormat: "Friday optimization segment",
      owner: "X Scale",
      scheduledFor: "Friday",
      output: "CPA/IC/ATC decision tree",
      next: "Teach the signal hierarchy during the first Friday live.",
    },
    {
      id: "t-006",
      title: "How to turn a member question into a live call topic",
      type: "Internal SOP",
      status: "Backlog",
      stage: "Community",
      priority: "P2",
      demand: 4,
      evidence: "We need a repeatable content ops process for the group.",
      source: "Dashboard build",
      recommendedFormat: "Admin SOP",
      owner: "Dashboard",
      scheduledFor: "Later",
      output: "Question-to-topic workflow",
      next: "Document the weekly review process after Friday.",
    },
  ],
  lives: [
    {
      day: "Monday",
      title: "New Offer Launch With AI",
      status: "Planned",
      owner: "X Scale",
      deliverable: "Offer decision, page brief, launch angle",
      metric: "Offer chosen",
      next: "Use real store and ad data to pick the week-one offer.",
    },
    {
      day: "Tuesday",
      title: "New Ad Launch With AI",
      status: "Ready",
      owner: "X Scale",
      deliverable: "Named static Meta ad batch",
      metric: "Ads launched",
      next: "Create the first batch in Odyssey and launch or prepare the test.",
    },
    {
      day: "Friday",
      title: "Ad Optimization With AI",
      status: "Queued",
      owner: "X Scale",
      deliverable: "Kill, keep, iterate, update batch",
      metric: "Next action set",
      next: "Review live data and turn the strongest signal into the next batch.",
    },
  ],
  content: [
    {
      id: "c-001",
      date: "2026-05-20",
      title: "Building IBD Assist's offer from real data",
      owner: "Devin",
      channel: "@devinmerkel",
      platform: "TikTok",
      url: "",
      source: "Live Clip",
      format: "Screen share",
      hook: "We are building the offer from scratch",
      views: 12400,
      likes: 318,
      comments: 44,
      shares: 28,
      saves: 86,
      joins: 19,
      status: "Winner",
      next: "Cut into 3 shorter hook variations",
    },
    {
      id: "c-002",
      date: "2026-05-20",
      title: "Landing page with AI in 10 minutes",
      owner: "Devin",
      channel: "@devinmerkel",
      platform: "Instagram Reels",
      url: "",
      source: "Founder Organic",
      format: "Talking + screen",
      hook: "A first draft is better than a blank page",
      views: 8700,
      likes: 221,
      comments: 31,
      shares: 17,
      saves: 74,
      joins: 12,
      status: "Promising",
      next: "Remake with the real IBD Assist page",
    },
    {
      id: "c-003",
      date: "2026-05-19",
      title: "Odyssey ad batch naming demo",
      owner: "X Scale",
      channel: "@xscale",
      platform: "YouTube Shorts",
      url: "",
      source: "Odyssey Demo",
      format: "Screen share",
      hook: "Your ad names should make Friday easier",
      views: 5200,
      likes: 118,
      comments: 18,
      shares: 9,
      saves: 41,
      joins: 7,
      status: "Useful",
      next: "Turn into a course lesson",
    },
    {
      id: "c-004",
      date: "2026-05-18",
      title: "Why most ecommerce teams test too slowly",
      owner: "Austin",
      channel: "@austinnormanads",
      platform: "TikTok",
      url: "",
      source: "Founder Organic",
      format: "Talking head",
      hook: "Slow testing is a growth tax",
      views: 16200,
      likes: 451,
      comments: 62,
      shares: 36,
      saves: 102,
      joins: 24,
      status: "Winner",
      next: "Make a version with IBD Assist visuals",
    },
    {
      id: "c-005",
      date: "2026-05-18",
      title: "Friday optimization decision tree",
      owner: "X Scale",
      channel: "@xscale",
      platform: "Instagram Reels",
      url: "",
      source: "Course Clip",
      format: "Whiteboard",
      hook: "CPA first, then the next best signal",
      views: 3900,
      likes: 95,
      comments: 12,
      shares: 11,
      saves: 49,
      joins: 5,
      status: "Save Magnet",
      next: "Post as Skool resource",
    },
  ],
  groupPosts: [
    {
      id: "g-001",
      title: "What product should I start with for the AI sprint?",
      category: "Questions",
      author: "New member",
      comments: 9,
      likes: 18,
      status: "Needs reply",
      signal: "Members need product selection rules",
      action: "Create a 5-minute Start Here lesson",
    },
    {
      id: "g-002",
      title: "Share your offer for this week",
      category: "Implementation",
      author: "Admin",
      comments: 27,
      likes: 41,
      status: "Active",
      signal: "Offer posts drive participation",
      action: "Pin during Monday live",
    },
    {
      id: "g-003",
      title: "Can Odyssey launch the ads or only write them?",
      category: "Odyssey",
      author: "Member",
      comments: 6,
      likes: 14,
      status: "Needs reply",
      signal: "Launch management must be explained",
      action: "Clip Tuesday launch section",
    },
    {
      id: "g-004",
      title: "Landing page before and after thread",
      category: "Wins",
      author: "Admin",
      comments: 12,
      likes: 33,
      status: "Active",
      signal: "People want visible builds",
      action: "Add IBD Assist screenshots",
    },
  ],
  experiments: [
    {
      week: "Week 1",
      offer: "First growth offer",
      page: "Page brief pending",
      ads: "Tuesday batch pending",
      status: "Planning",
      signal: "Need baseline store and ad analysis",
      next: "Choose the launch offer on Monday",
    },
    {
      week: "Week 2",
      offer: "Day/night routine or bundle",
      page: "Routine page variation",
      ads: "Wide Style Ideas then launch batch",
      status: "Queued",
      signal: "Use Week 1 performance",
      next: "Compare angles and product signals",
    },
    {
      week: "Week 3",
      offer: "60-day routine or subscription",
      page: "LTV page section",
      ads: "Prospecting and retargeting",
      status: "Queued",
      signal: "Use first two weeks of learning",
      next: "Build the next 30-day roadmap",
    },
  ],
  integrations: [
    {
      name: "Skool",
      status: "Official Zapier first / optional SkoolAPI",
      priority: "P0",
      note: "Use Zapier for membership questions and paid member events. Use optional SkoolAPI or notification parsing for posts, comments, unanswered questions, and top threads.",
    },
    {
      name: "YouTube Shorts",
      status: "API-ready",
      priority: "P0",
      note: "Pull views, likes, comments, shares, and watch data where available.",
    },
    {
      name: "Instagram Reels",
      status: "Meta permissions needed",
      priority: "P0",
      note: "Pull reach, interactions, saves, shares, and post-level performance.",
    },
    {
      name: "TikTok",
      status: "Export or connector",
      priority: "P1",
      note: "Start with manual exports or approved API access; official analytics access is more restricted than YouTube and Meta.",
    },
    {
      name: "Odyssey",
      status: "Product data source",
      priority: "P0",
      note: "Track token usage, top-ups, ad batches generated, launches, and analysis runs.",
    },
    {
      name: "Meta Ads",
      status: "Future API",
      priority: "P0",
      note: "Pull launch performance and tie it to the weekly IBD Assist experiments.",
    },
  ],
  actions: [
    {
      label: "Build the first IBD Assist offer page brief",
      owner: "Monday Live",
      urgency: "High",
    },
    {
      label: "Create the content tagging rules",
      owner: "Dashboard",
      urgency: "High",
    },
    {
      label: "Decide which replays become Pro-only after launch",
      owner: "Strategy",
      urgency: "Medium",
    },
    {
      label: "Add Odyssey token/top-up metrics when available",
      owner: "Product",
      urgency: "Medium",
    },
  ],
};
